name: dav1d
on:
  push:
    branches:
      - main
    paths:
      - '.github/matrix*.json'
      - '.github/workflows/_matrix.yml'
      - '.github/workflows/dav1d.yml'
      - 'patches/dav1d/**'
      - 'scripts/dav1d.py'
      - 'build.py'
  pull_request:
    branches:
      - main
    paths:
      - '.github/matrix*.json'
      - '.github/workflows/_matrix.yml'
      - '.github/workflows/dav1d.yml'
      - 'patches/dav1d/**'
      - 'scripts/dav1d.py'
      - 'build.py'

jobs:
  build:
    if: ${{ false }}
    secrets: inherit
    uses: ./.github/workflows/_matrix.yml
    with:
      select_platforms: "macosx, linux"
