name: ffmpeg
on:
  workflow_dispatch:
    inputs:
      disable_shared:
        default: true
        required: false
        type: boolean
  push:
    branches:
      - main
    paths:
      - '.github/workflows/_matrix.yml'
      - '.github/workflows/ffmpeg.yml'
      - 'deps/ffmpeg'
      - 'patches/ffmpeg/**'
      - 'scripts/ffmpeg.sh'
      - 'build.sh'
      - 'env-apple.sh'
      - 'pkg-conf.sh'
  pull_request:
    branches:
      - main
    paths:
      - '.github/workflows/_matrix.yml'
      - '.github/workflows/ffmpeg.yml'
      - 'deps/ffmpeg'
      - 'patches/ffmpeg/**'
      - 'scripts/ffmpeg.sh'
      - 'build.sh'
      - 'env-apple.sh'
      - 'pkg-conf.sh'

jobs:
  build:
    secrets: inherit
    uses: ./.github/workflows/_matrix.yml
    with:
      disable_shared: ${{ inputs.disable_shared }}
      disable_upload: true
