name: ffmpeg
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - '.github/matrix*.json'
      - '.github/workflows/_matrix.yml'
      - '.github/workflows/ffmpeg.yml'
      - 'deps/ffmpeg'
      - 'patches/ffmpeg/**'
      - 'scripts/ffmpeg.sh'
      - 'build.sh'
      - 'env-*.sh'
      - 'pkg-conf.sh'
  pull_request:
    branches:
      - main
    paths:
      - '.github/matrix*.json'
      - '.github/workflows/_matrix.yml'
      - '.github/workflows/ffmpeg.yml'
      - 'deps/ffmpeg'
      - 'patches/ffmpeg/**'
      - 'scripts/ffmpeg.sh'
      - 'build.sh'
      - 'env-*.sh'
      - 'pkg-conf.sh'

jobs:
  build:
    secrets: inherit
    uses: ./.github/workflows/_matrix.yml
    with:
      allow_failure: true
      only_executable: true
