name: ffmpeg
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - '.github/*.py'
      - '.github/matrix*.json'
      - '.github/workflows/_matrix.yml'
      - '.github/workflows/ffmpeg.yml'
      - 'patches/ffmpeg/**'
      - 'scripts/ffmpeg.py'
      - 'build.py'
  pull_request:
    branches:
      - main
    paths:
      - '.github/*.py'
      - '.github/matrix*.json'
      - '.github/workflows/_matrix.yml'
      - '.github/workflows/ffmpeg.yml'
      - 'patches/ffmpeg/**'
      - 'scripts/ffmpeg.py'
      - 'build.py'

jobs:
  build:
    # if: ${{ false }}
    secrets: inherit
    uses: ./.github/workflows/_matrix.yml
    with:
      disable_commit: true
      disable_ccache: false
      select_platforms: "macosx, linux, win-mingw, android"
