name: ffmpeg
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - '.github/matrix*.json'
      - '.github/workflows/_matrix.yml'
      - '.github/workflows/ffmpeg.yml'
      - 'deps/ffmpeg'
      - 'patches/ffmpeg/**'
      - 'scripts/ffmpeg.sh'
      - 'scripts/ffmpeg.ps1'
      - 'build.sh'
      - 'build.ps1'
      - 'env-*.sh'
      - 'env-*.ps1'
      - 'pkg-conf.sh'
      - 'pkg-conf.ps1'
  pull_request:
    branches:
      - main
    paths:
      - '.github/matrix*.json'
      - '.github/workflows/_matrix.yml'
      - '.github/workflows/ffmpeg.yml'
      - 'deps/ffmpeg'
      - 'patches/ffmpeg/**'
      - 'scripts/ffmpeg.sh'
      - 'scripts/ffmpeg.ps1'
      - 'build.sh'
      - 'build.ps1'
      - 'env-*.sh'
      - 'env-*.ps1'
      - 'pkg-conf.sh'
      - 'pkg-conf.ps1'

jobs:
  build:
    # if: ${{ false }}
    secrets: inherit
    uses: ./.github/workflows/_matrix.yml
    with:
      disable_commit: true
      select_platforms: "macosx, linux"
