name: libexpat
on:
  push:
    branches:
      - main
    paths:
      - '.github/*.py'
      - '.github/matrix*.json'
      - '.github/workflows/_matrix.yml'
      - '.github/workflows/libexpat.yml'
      - 'patches/libexpat/**'
      - 'scripts/libexpat.py'
      - 'build.py'
  pull_request:
    branches:
      - main
    paths:
      - '.github/*.py'
      - '.github/matrix*.json'
      - '.github/workflows/_matrix.yml'
      - '.github/workflows/libexpat.yml'
      - 'patches/libexpat/**'
      - 'scripts/libexpat.py'
      - 'build.py'

jobs:
  build:
    # if: ${{ false }}
    secrets: inherit
    uses: ./.github/workflows/_matrix.yml
    with:
      skip_platform_apple: true
