name: libjpeg80
on:
  push:
    branches:
      - main
    paths:
      - '.github/*.py'
      - '.github/matrix*.json'
      - '.github/workflows/_matrix.yml'
      - '.github/workflows/libjpeg80.yml'
      - 'patches/libjpeg80/**'
      - 'scripts/libjpeg80.py'
      - 'build.py'
  pull_request:
    branches:
      - main
    paths:
      - '.github/*.py'
      - '.github/matrix*.json'
      - '.github/workflows/_matrix.yml'
      - '.github/workflows/libjpeg80.yml'
      - 'patches/libjpeg80/**'
      - 'scripts/libjpeg80.py'
      - 'build.py'

jobs:
  build:
    # if: ${{ false }}
    secrets: inherit
    uses: ./.github/workflows/_matrix.yml
