name: libpng16
on:
  push:
    branches:
      - main
    paths:
      - '.github/matrix*.json'
      - '.github/workflows/_matrix.yml'
      - '.github/workflows/libpng16.yml'
      - 'deps/libpng16'
      - 'patches/libpng16/**'
      - 'scripts/libpng16.sh'
      - 'scripts/libpng16.ps1'
      - 'build.sh'
      - 'build.ps1'
      - 'env-*.sh'
      - 'env-*.ps1'
      - 'pkg-conf.sh'
      - 'pkg-conf.ps1'
  pull_request:
    branches:
      - main
    paths:
      - '.github/matrix*.json'
      - '.github/workflows/_matrix.yml'
      - '.github/workflows/libpng16.yml'
      - 'deps/libpng16'
      - 'patches/libpng16/**'
      - 'scripts/libpng16.sh'
      - 'scripts/libpng16.ps1'
      - 'build.sh'
      - 'build.ps1'
      - 'env-*.sh'
      - 'env-*.ps1'
      - 'pkg-conf.sh'
      - 'pkg-conf.ps1'

jobs:
  build:
    if: ${{ false }}
    secrets: inherit
    uses: ./.github/workflows/_matrix.yml
