name: libpng16
on:
  push:
    branches:
      - main
    paths:
      - '.github/*.py'
      - '.github/matrix*.json'
      - '.github/workflows/_matrix.yml'
      - '.github/workflows/libpng16.yml'
      - 'patches/libpng16/**'
      - 'scripts/libpng16.py'
      - 'build.py'
  pull_request:
    branches:
      - main
    paths:
      - '.github/*.py'
      - '.github/matrix*.json'
      - '.github/workflows/_matrix.yml'
      - '.github/workflows/libpng16.yml'
      - 'patches/libpng16/**'
      - 'scripts/libpng16.py'
      - 'build.py'

jobs:
  build:
    # if: ${{ false }}
    secrets: inherit
    uses: ./.github/workflows/_matrix.yml
