name: llvm
on:
  workflow_dispatch:

jobs:
  build:
    # if: ${{ false }}
    secrets: inherit
    uses: ./.github/workflows/_matrix.yml
    with:
      disable_commit: true
      select_platforms: "macosx, linux, win-msvc"
