name: llvm
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - '.github/matrix*.json'
      - '.github/workflows/_matrix.yml'
      - '.github/workflows/llvm.yml'
      - 'deps/llvm'
      - 'patches/llvm/**'
      - 'scripts/llvm.sh'
      - 'build.sh'
      - 'env-*.sh'
      - 'pkg-conf.sh'
  pull_request:
    branches:
      - main
    paths:
      - '.github/matrix*.json'
      - '.github/workflows/_matrix.yml'
      - '.github/workflows/llvm.yml'
      - 'deps/llvm'
      - 'patches/llvm/**'
      - 'scripts/llvm.sh'
      - 'build.sh'
      - 'env-*.sh'
      - 'pkg-conf.sh'

jobs:
  build:
    secrets: inherit
    uses: ./.github/workflows/_matrix.yml
    with:
      disable_commit: true
      allow_failure: true
      host_executable: true
      container_linux: "linux310-gcc7"
