name: llvm
on:
  push:
    branches:
      - main
    paths:
      - '.github/*.py'
      - '.github/matrix*.json'
      - '.github/workflows/_matrix.yml'
      - '.github/workflows/llvm.yml'
      - 'patches/llvm/**'
      - 'scripts/llvm.py'
      - 'build.py'
  pull_request:
    branches:
      - main
    paths:
      - '.github/*.py'
      - '.github/matrix*.json'
      - '.github/workflows/_matrix.yml'
      - '.github/workflows/llvm.yml'
      - 'patches/llvm/**'
      - 'scripts/llvm.py'
      - 'build.py'

jobs:
  build:
    # if: ${{ false }}
    secrets: inherit
    uses: ./.github/workflows/_matrix.yml
    with:
      disable_commit: true
      disable_ccache: false
      container_linux: "linux310-gcc7"
      select_platforms: "macosx, linux, win-msvc"
