name: llvm
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - '.github/matrix*.json'
      - '.github/workflows/_matrix.yml'
      - '.github/workflows/llvm.yml'
      - 'deps/llvm'
      - 'patches/llvm/**'
      - 'scripts/llvm.sh'
      - 'scripts/llvm.ps1'
      - 'build.sh'
      - 'build.ps1'
      - 'env-*.sh'
      - 'env-*.ps1'
      - 'pkg-conf.sh'
      - 'pkg-conf.ps1'
  pull_request:
    branches:
      - main
    paths:
      - '.github/matrix*.json'
      - '.github/workflows/_matrix.yml'
      - '.github/workflows/llvm.yml'
      - 'deps/llvm'
      - 'patches/llvm/**'
      - 'scripts/llvm.sh'
      - 'scripts/llvm.ps1'
      - 'build.sh'
      - 'build.ps1'
      - 'env-*.sh'
      - 'env-*.ps1'
      - 'pkg-conf.sh'
      - 'pkg-conf.ps1'

jobs:
  build:
    # if: ${{ false }}
    secrets: inherit
    uses: ./.github/workflows/_matrix.yml
    with:
      disable_commit: true
      container_linux: "linux310-gcc7"
      select_platforms: "macosx, linux"
