name: mbedtls3
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - '.github/matrix*.json'
      - '.github/workflows/_matrix.yml'
      - '.github/workflows/mbedtls3.yml'
      - 'patches/mbedtls3/**'
      - 'modules/mbedtls3.py'
  pull_request:
    branches:
      - main
    paths:
      - '.github/matrix*.json'
      - '.github/workflows/_matrix.yml'
      - '.github/workflows/mbedtls3.yml'
      - 'patches/mbedtls3/**'
      - 'modules/mbedtls3.py'

jobs:
  build:
    # if: ${{ false }}
    secrets: inherit
    uses: ./.github/workflows/_matrix.yml
    with:
      disable_shared: true
      enable_static_commit: true
