name: mbedtls4
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - '.github/*.py'
      - '.github/matrix*.json'
      - '.github/workflows/_matrix.yml'
      - '.github/workflows/mbedtls4.yml'
      - 'patches/mbedtls4/**'
      - 'modules/mbedtls4.py'
      - 'build.py'
  pull_request:
    branches:
      - main
    paths:
      - '.github/*.py'
      - '.github/matrix*.json'
      - '.github/workflows/_matrix.yml'
      - '.github/workflows/mbedtls4.yml'
      - 'patches/mbedtls4/**'
      - 'modules/mbedtls4.py'
      - 'build.py'

jobs:
  build:
    # if: ${{ false }}
    secrets: inherit
    uses: ./.github/workflows/_matrix.yml
