name: openvpn
on:
  workflow_dispatch:

jobs:
  build:
    # if: ${{ false }}
    secrets: inherit
    uses: ./.github/workflows/_matrix.yml
    with:
      disable_commit: true
      disable_ccache_on_container: true
      select_platforms: "macosx"
