name: sdl2
on:
  push:
    branches:
      - main
    paths:
      - '.github/matrix*.json'
      - '.github/workflows/_matrix.yml'
      - '.github/workflows/sdl2.yml'
      - 'deps/sdl2'
      - 'patches/sdl2/**'
      - 'scripts/sdl2.sh'
      - 'build.sh'
      - 'env-*.sh'
  pull_request:
    branches:
      - main
    paths:
      - '.github/matrix*.json'
      - '.github/workflows/_matrix.yml'
      - '.github/workflows/sdl2.yml'
      - 'deps/sdl2'
      - 'patches/sdl2/**'
      - 'scripts/sdl2.sh'
      - 'build.sh'
      - 'env-*.sh'

jobs:
  build:
    # if: ${{ false }}
    secrets: inherit
    uses: ./.github/workflows/_matrix.yml
    with:
      select_platforms: "macosx, win-mingw, win-msvc"
