name: sdl2
on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/_matrix.yml'
      - '.github/workflows/sdl2.yml'
      - 'deps/sdl2'
      - 'patchs/sdl2/**'
      - 'scripts/sdl2.sh'
      - 'build.sh'
      - 'env-apple.sh'
  pull_request:
    branches:
      - main
    paths:
      - '.github/workflows/_matrix.yml'
      - '.github/workflows/sdl2.yml'
      - 'deps/sdl2'
      - 'patchs/sdl2/**'
      - 'scripts/sdl2.sh'
      - 'build.sh'
      - 'env-apple.sh'

jobs:
  build:
    secrets: inherit
    uses: ./.github/workflows/_matrix.yml
